"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from dotenv import load_dotenv
from split_settings.tools import include

load_dotenv()

include(
    'components/installed_apps.py',
)

include(
    'components/middleware.py',
)

include(
    'components/templates.py',
)

include(
    'components/database.py',
)

include(
    'components/auth_password_validators.py',
)

include(
    'components/constants.py',
)
